// Replays webGame/tests/fixtures/parity.json (generated by
// gen_parity_fixtures.php from the real PHP engine) through the JS rules
// mirror in webGame/js/data.js and asserts they agree. Turns silent PHP<->JS
// rules drift (docs/webgame_code_review.md §3.3) into a failing test.
// Usage: node webGame/tools/test_parity.mjs
// Regenerate fixtures first if data.js or the PHP rules changed:
//   php webGame/tools/gen_parity_fixtures.php > webGame/tests/fixtures/parity.json

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// data.js's loadCards() fetches 'data/cards.json' relative to the page URL in
// the browser; serve the same file from disk here instead of faking a server.
const cardsPath = path.join(__dirname, '../data/cards.json');
globalThis.fetch = async () => ({ json: async () => JSON.parse(readFileSync(cardsPath, 'utf8')) });

const { loadCards, craftReliability, passiveLanding, checkMission, simulatePlan } =
  await import('../js/data.js');
await loadCards();

const fixturesPath = path.join(__dirname, '../tests/fixtures/parity.json');
const fixtures = JSON.parse(readFileSync(fixturesPath, 'utf8'));

let pass = 0, fail = 0;
function ok(cond, label) {
  if (cond) { pass++; console.log(`  ✔ ${label}`); }
  else { fail++; console.log(`  ✘ FAIL: ${label}`); }
}
function eq(actual, expected, label) {
  const a = JSON.stringify(actual), e = JSON.stringify(expected);
  ok(a === e, `${label} (got ${a}, want ${e})`);
}

console.log('— Reliability parity (craftReliability vs sar_craft_reliability)');
for (const fx of fixtures.reliability) {
  const [rel, mods] = craftReliability(fx.g, fx.craft, fx.useFc);
  eq({ rel, mods }, fx.expect, fx.label);
}

console.log('\n— Passive-landing parity (passiveLanding vs sar_passive_landing)');
for (const fx of fixtures.landing) {
  const label = passiveLanding(fx.craft, fx.surface);
  const crashes = label === null;
  ok(crashes === fx.expect.crashes, `${fx.label}: crashes=${crashes} (want ${fx.expect.crashes})`);
  if (fx.expect.cardName !== null) {
    ok(label === fx.expect.cardName, `${fx.label}: label "${label}" (want "${fx.expect.cardName}")`);
  }
}

console.log('\n— Mission-check parity (checkMission vs sar_mission_check)');
for (const fx of fixtures.missions) {
  const result = checkMission(fx.g, fx.mid, fx.craft);
  ok(!!result === fx.expect, `${fx.label}: ${!!result} (want ${fx.expect})`);
}

console.log('\n— Flight-plan parity (simulatePlan vs sar_run_flight dry-run)');
for (const fx of fixtures.plan) {
  const res = simulatePlan(fx.g, fx.craft, fx.plan);
  if (fx.expect.ok) {
    ok(res.ok, `${fx.label}: ok=${res.ok} (want true)` + (res.ok ? '' : ` — error: ${res.error}`));
    if (res.ok) {
      const fc = res.finalCraft;
      eq({ node: fc.node, range: fc.range, energy: fc.energy, history: fc.history, docked: fc.docked },
        fx.expect.finalCraft, `${fx.label}: final craft state`);
    }
  } else {
    ok(!res.ok, `${fx.label}: ok=${res.ok} (want false)`);
  }
}

console.log(`\n${pass} passed, ${fail} failed.`);
process.exit(fail > 0 ? 1 : 0);
